trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      set -e
      echo "Installing dependencies..."
      npm install && npm run client-install
      
      echo "Downloading and installing Snyk CLI..."
      curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
      chmod +x ./snyk
      sudo mv ./snyk /usr/local/bin/
      
      echo "Installing snyk-to-html..."
      sudo npm install -g snyk-to-html
      
      echo "Creating results directory..."
      mkdir -p results
      
      echo "Authenticating with Snyk..."
      snyk auth $(SNYK_TOKEN)
      
      echo "Running security scans..."
      snyk test --all-projects --json-file-output=results/oss.json || true
      snyk code test --sarif-file-output=results/sast.sarif || true
      
      echo "Converting results to HTML..."
      snyk-to-html -o results/oss.html < results/oss.json || true
      snyk-to-html -o results/sast.html < results/sast.sarif || true
      
      echo "Security scans completed."
    env:
      SNYK_TOKEN: $(SNYK_TOKEN)
    displayName: 'Security Scans'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/results'
      ArtifactName: 'security-scan-results'
      publishLocation: 'Container'